name: Nils Smith
favicon: null
layout_spectrum: 0.5969845282379538
typography_spectrum: 0.5302094426006079
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6187390882987529
  lightness: 0.8231991685461253
  saturation: 0.4015052549075335
  rhythmicContrast: 0.352918547578156
purpose: []
